### PR TITLE
sys: update upstream Gems

### PR DESCRIPTION
**Pull request by george-angel**

### CODE REVIEW

**Review by hectorhuertas — COMMENTED** [review]
Crossing fingers they all work together. I think fluentd latest is 1.2.5

**Comment by george-angel** [comment]
I'll leave this open for now and try it out in exp-1-aws and see how it fairs, will merge once happy. Image available: `quay.io/utilitywarehouse/fluentd:upstream-gems`

**Comment by hectorhuertas** [comment]
👍

**Comment by george-angel** [comment]
This is now running in exp-1-aws without any issues

**Pull request merged**
