### PR TITLE
Add fluent-plugin-gcs~>0.4.0.beta1, latest stable (0.3) raising conflict

### PR DESCRIPTION
**Pull request by ffilippopoulos**
last stable version (0.3.0) is giving me:
```
ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies fluentd (~> 0.12.0) and fluentd (>= 0.12.0)
  Activated fluentd-1.1.0
  which does not match conflicting dependency (~> 0.12.0)

  Conflicting dependency chains:
    fluent-plugin-kubernetes_metadata_filter (~> 1.0.0), 1.0.3 activated, depends on
    fluentd (>= 0.12.0), 1.1.0 activated

  versus:
    fluent-plugin-gcs (~> 0.3.0), 0.3.0 activated, depends on
    fluentd (~> 0.12.0)
```

### CODE REVIEW

**Review by hectorhuertas — APPROVED** [review]
Considering that the beta version is a year old, shouldn't be too risky

**Comment by george-angel** [comment]
What is this for?

**Comment by ffilippopoulos** [comment]
We use a bucket to push logs from `kube-api-server`, and that is a plugin that allows fluentd to push to gcp buckets.

**Comment by george-angel** [comment]
Ah of course, thanks

**Review by george-angel — APPROVED** [review]

**Pull request merged**
